FROM node:18-slim as builder

WORKDIR /app
# COPY package*.json ./
# RUN npm install --include=dev
COPY . .
# RUN npm run build -- --outDir dist

FROM nginx:stable-alpine
COPY --from=builder /app/index.html /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]